resources:
- backend/deployment.yml
- backend/service.yml
- frontend/deployment.yml
- frontend/service.yml

images:
- name: 874026451845.dkr.ecr.us-east-1.amazonaws.com/workshop-dvn/production/backend
  newName: 874026451845.dkr.ecr.us-east-1.amazonaws.com/workshop-dvn/production/backend
  newTag: v1.0

- name: 874026451845.dkr.ecr.us-east-1.amazonaws.com/workshop-dvn/production/frontend
  newName: 874026451845.dkr.ecr.us-east-1.amazonaws.com/workshop-dvn/production/frontend
  newTag: v1.0